<?php
use Zend\Form\Element;
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Add User</h3>
  </div>
  <div class="panel-body">
  
  <?php
	if($this->error){
?>
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<strong> Error </strong> The following errors have occurred: 
	<ul>
	<?php 
	  foreach ($this->error as $key=>$value):
	 ?>
	 	<?php if(is_array($value)): ?>
	 		<?php foreach ($value as $k=>$v): ?>
	 		<li> <?php echo $key.' '.$k.' : '.$v;  ?> </li>
	 		<?php endforeach; ?>
	 	<?php else: ?>
	 	<li><?php echo $value; ?> </li>
	 	<?php endif; ?>
	<?php
	  endforeach;
	 ?>
	 </ul>
</div>
<?php } ?>

<div id="searchContent"></div>

  		<?php 
  		$form = $this->form;
  		$form->prepare();
  		echo $this->form()->openTag($form);
  		?>
<fieldset>
    <legend>General Information</legend>  		
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">First Name:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('first_name');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">Last Name:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('last_name');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">Email:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('email');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">Ldap identity:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('ldap_identity');
				    echo $this->formInput($name);
				?>
				
				&nbsp;<?php echo $this->formElement($form->get('search_ldap')) ?>
				<small style="display:block;">Please make sure that Ldap identity and email are used by same user, otherwise user can't login via Ldap . please leave it blank if you don't want this user login via Ldap</small>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">Password:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('newPassword');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <label for="inputId" class="col-sm-2 control-label">Confirm Password:</label>
		    <div class="col-sm-10">
		    	<?php
				    $name = $form->get('newConfirmPassword');
				    echo $this->formInput($name);
				?>
		    </div>
		  </div>
		  
		  <div class="form-group">
		  <label for="inputId" class="col-sm-2 control-label"></label>
		  <div class="col-sm-10">
		  <?php echo $this->formElement($form->get('submit')) ?>&nbsp;<?php echo $this->formElement($form->get('cancel')) ?>
		  </div>
		  </div>		   	
		<?php echo $this->formElement($form->get('id')) ?>
</fieldset>		
		<?php echo $this->form()->closeTag() ?>
</div>
</div>
<script type="text/javascript">
(function($){
	$(function(){
		
		$('#search_ldap').click(function(){
			$("#searchContent").load("/auth/search");
		});

	});
})(jQuery);
</script>