<?php
use Zend\Form\Element;
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">ADMININSTRATOR LOGIN</h3>
  </div>
  <div class="panel-body">
<?php echo $this->render("layout/udferror"); ?>
<form action="/auth/login" class="form-signin" role="form" method="post">
	<h2 class="form-signin-heading">Please Log in</h2>
 <div class="form-group">
<?php
$element = new Element\Text ( "adminUsername" );
$element->setAttributes ( array (
		'class' => 'form-control',
		'placeholder' => 'Username',
		'required' => 'true',
		'autofocus' => 'true',
		'style'=>'width:100%;' 
) );

echo $this->formText ( $element );
?>
</div>
 <div class="form-group">
<?php 
$element = new Element\Password ( "adminPassword" );
$element->setAttributes ( array (
		'class' => 'form-control',
		'placeholder' => 'Password',
		'required' => 'true',
		'autofocus' => 'true',
		'style'=>'width:100%;'
		 
) );
?>
</div>
 <div class="form-group">
<?php
echo $this->formpassword ( $element );

$element = new Element\Radio ( "adapter" );

$element->setAttributes ( array (
		'value' => 'default' 
) );

?>
</div>
<!--  <div  class="form-group">
	<label  for="inlineRadio1" class="radio-inline"> 
		<input type="radio" name="adapter" id="inlineRadio1" value="default">default
	</label> 
	<label  for="inlineRadio2" class="radio-inline"> 
		<input type="radio" name="adapter" id="inlineRadio2" value="ldap">ldap
	</label>
</div>-->
<div  class="form-group">
	<button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
</div>
</form>

</div>
</div>