<?
if($this->isPost && empty($this->status)):
?>
	A message has been sent to your e-mail address. Please check your inbox.
<?
else:
?>
<div class="member-wrapper">
<BR>
    <h1>Forgot password</h1>
    <?php 
    	$passwordRecoveryUrl = $this->GetUrl('password_recovery');
    ?>
    <form action="<?=$passwordRecoveryUrl;?>" method="post">
    <?php
    	if(!empty($this->status)):
    ?>
    	<p class="error-text" id="errors">
	    <?php
	    	foreach ($this->status as $item):
	    		echo $this->escapehtml($item);
	    ?>
	    	<br/>
	    <?php
	    	endforeach;
	    ?>
	    	</p>
    <?php
    	endif;
    ?>
	    <div class="box-blue">
	        <div class="box-content">
	            <label for="email">
	                Your email address
	            </label>
	            <input type="text" value="<?=$this->email?>" name="email" id="email"/> 
	            <input type="submit" value="Send email"/>
	        </div>
	    </div>
	    <?php echo $this->formElement($this->csrf); ?>
    </form>
    <div class="box-info">
    	<h2>Please follow these simple steps to rest your password:</h2>
    	<ol>
    		<li>Enter the email address you used to sign up and click Send email</li>
    		<li>You'll then receive an email with a link to rest your password.</li>
    		<li>Then just enter your new password and hit Submit.</li>
    	</ol>
	</div>
</div>
<?
endif;
?>