<div class="member-wrapper">
<?php
	if($this->keyInValid):
?>
    <h1>Password reset</h1>
    The link you used to get here was either invalid or expired, please go back and request a new activation email
<?php
	else:
		if($this->isPost && empty($this->status)):
?>
		<h1>Password reset</h1>
    	Your password has been reset and you can now log in using your new password
    <?php
    	else:
    ?>
	    <h1>Password reset</h1>
	<?php
		if(!empty($this->status)):
	?>
	    <p class="error-text" id="errors">
	    <?php
	    	foreach ($this->status as $item):
	    		echo $this->escapehtml($item);
	    ?>
	    	<br/>
	    <?php
	    	endforeach;
	    ?>
	    	</p>
	<?php
		endif;
			$passwordResetUrl = $this->GetUrl('password_reset',array(),array('key'=>$this->key));
	?>
	    <form action="<?=$passwordResetUrl;?>" method="post">
	        <div class="box-red">
	        	<div class="box-content">
	             <div class="content-left">
	                 <label for="password">
	                 	Create new password:
	                 </label>
	                 <input type="password" value="" class="input fullwidth" name="password" id="password"/>
	                 <span class="info-text">Please use more than 6 characters including numbers and letters</span>
	             </div>
	             <div class="content-right">
	                 <label for="password">
	                 	Re-enter new password:
	                 </label>
	                 <input type="password" value="" class="input fullwidth" name="passwordRepeat" id="passwordRepeat"/>
	                 <span class="info-text"> </span>
	             </div>
	        	</div>
	        </div>
	        <div class="box-free">
	            <input type="submit" value="Save new password" class="submit"/>
	        </div>
	    </form>   
    <?php
    	endif;
	endif;
?>
</div>