<style type="text/css">
fieldset.scheduler-border {
    border: 1px groove #ddd !important;
    padding: 0 1.4em 1.4em 1.4em !important;
    margin: 0 0 1.5em 0 !important;
    -webkit-box-shadow:  0px 0px 0px 0px #000;
            box-shadow:  0px 0px 0px 0px #000;
}

legend.scheduler-border {
    font-size: 1.5em !important;
    font-weight: bold !important;
    text-align: left !important;
    width:inherit; /* Or auto */
    padding:0 10px; /* To give a bit of padding on the left and right */
    border-bottom:none;
    margin:10px 0;
}
</style>
<?
foreach ($this->data as $item):

?>

<div class="row">
    <div class="col-sm-12">
        <fieldset class="scheduler-border">
            <legend class="scheduler-border"><?=$item['name']?></legend>
            
            <h5>
            	<strong>Description: </strong>
            	<?=$item['info']?>
           	</h5>
            
            <form action="/memcache" method="post">
            	<input type="hidden" name="flush" value="<?=$item['type']?>" />
            	<input type="submit" name="submit" value="Flush" class="btn btn-primary" />
                <span style="color: red;"><?=$item['flushed'] ? "Flushed successfully!" : ""?></span>
                <span style="color: red;"><?=$item['resultInfo'] ? $item['resultInfo'] : ""?></span>
            </form>
        </fieldset>
    </div>
</div>




<?endforeach;?>